### ISSUE TITLE
Does not compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by mmaurus** [rock-slam/slam-envire#10]
Usage of deprecated methods, which are now removed from CGAL (version 4.13 defaulting on Ubuntu 18.04) like CGAL::Triangulation_euclidean_traits_xy_3<K> in src/operators/Projection.cpp prevents slam-envire from compiling.

**Comment by mmaurus** [comment]
Looks like replacing **typedef CGAL::Triangulation_euclidean_traits_xy_3<K>;**  Gt with **typedef CGAL::Projection_traits_xy_3<K> Gt;** makes it compile again.
But I am not sure about the functionality.
From my unterstanding, this should be the corresponding new function.
See also https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Projection__traits__xy__3.html

**Comment by chhtz** [comment]
Looks fine (on Ubuntu 16.04 the implementations of both traits are the same -- only the first is marked deprecated). Fixed in 2b6eb96bad1e9a.
